# TCL File Generated by Component Editor 9.1sp1
# Wed Aug 25 22:14:38 CST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | sdram_master "sdram_master" v1.0
# | null 2010.08.25.22:14:38
# | 
# | 
# | J:/lab_source/test/tv_master/ip/sdram_master/sdram_master.v
# | 
# |    ./sdram_master.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module sdram_master
# | 
set_module_property NAME sdram_master
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP user_logic
set_module_property DISPLAY_NAME sdram_master
set_module_property TOP_LEVEL_HDL_FILE sdram_master.v
set_module_property TOP_LEVEL_HDL_MODULE sdram_master
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file sdram_master.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter DMA_IDLE INTEGER 0
set_parameter_property DMA_IDLE DEFAULT_VALUE 0
set_parameter_property DMA_IDLE DISPLAY_NAME DMA_IDLE
set_parameter_property DMA_IDLE UNITS None
set_parameter_property DMA_IDLE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DMA_IDLE DISPLAY_HINT ""
set_parameter_property DMA_IDLE AFFECTS_GENERATION false
set_parameter_property DMA_IDLE HDL_PARAMETER true
add_parameter READ INTEGER 1
set_parameter_property READ DEFAULT_VALUE 1
set_parameter_property READ DISPLAY_NAME READ
set_parameter_property READ UNITS None
set_parameter_property READ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property READ DISPLAY_HINT ""
set_parameter_property READ AFFECTS_GENERATION false
set_parameter_property READ HDL_PARAMETER true
add_parameter WAIT_READ INTEGER 2
set_parameter_property WAIT_READ DEFAULT_VALUE 2
set_parameter_property WAIT_READ DISPLAY_NAME WAIT_READ
set_parameter_property WAIT_READ UNITS None
set_parameter_property WAIT_READ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WAIT_READ DISPLAY_HINT ""
set_parameter_property WAIT_READ AFFECTS_GENERATION false
set_parameter_property WAIT_READ HDL_PARAMETER true
add_parameter WRITE INTEGER 3
set_parameter_property WRITE DEFAULT_VALUE 3
set_parameter_property WRITE DISPLAY_NAME WRITE
set_parameter_property WRITE UNITS None
set_parameter_property WRITE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WRITE DISPLAY_HINT ""
set_parameter_property WRITE AFFECTS_GENERATION false
set_parameter_property WRITE HDL_PARAMETER true
add_parameter WAIT_WRITE INTEGER 4
set_parameter_property WAIT_WRITE DEFAULT_VALUE 4
set_parameter_property WAIT_WRITE DISPLAY_NAME WAIT_WRITE
set_parameter_property WAIT_WRITE UNITS None
set_parameter_property WAIT_WRITE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WAIT_WRITE DISPLAY_HINT ""
set_parameter_property WAIT_WRITE AFFECTS_GENERATION false
set_parameter_property WAIT_WRITE HDL_PARAMETER true
add_parameter CALC_NEXT INTEGER 5
set_parameter_property CALC_NEXT DEFAULT_VALUE 5
set_parameter_property CALC_NEXT DISPLAY_NAME CALC_NEXT
set_parameter_property CALC_NEXT UNITS None
set_parameter_property CALC_NEXT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CALC_NEXT DISPLAY_HINT ""
set_parameter_property CALC_NEXT AFFECTS_GENERATION false
set_parameter_property CALC_NEXT HDL_PARAMETER true
add_parameter DMA_DONE INTEGER 6
set_parameter_property DMA_DONE DEFAULT_VALUE 6
set_parameter_property DMA_DONE DISPLAY_NAME DMA_DONE
set_parameter_property DMA_DONE UNITS None
set_parameter_property DMA_DONE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DMA_DONE DISPLAY_HINT ""
set_parameter_property DMA_DONE AFFECTS_GENERATION false
set_parameter_property DMA_DONE HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1
# | 
add_interface s1 avalon end
set_interface_property s1 addressAlignment NATIVE
set_interface_property s1 associatedClock clock_reset
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 isMemoryDevice false
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 printableDevice false
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0

set_interface_property s1 ASSOCIATED_CLOCK clock_reset
set_interface_property s1 ENABLED true

add_interface_port s1 avs_s1_chipselect chipselect Input 1
add_interface_port s1 avs_s1_address address Input 3
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_readdata readdata Output 32
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_byteenable byteenable Input 4
add_interface_port s1 avs_s1_waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point read
# | 
add_interface read avalon start
set_interface_property read associatedClock clock_reset
set_interface_property read burstOnBurstBoundariesOnly false
set_interface_property read doStreamReads false
set_interface_property read doStreamWrites false
set_interface_property read linewrapBursts false

set_interface_property read ASSOCIATED_CLOCK clock_reset
set_interface_property read ENABLED true

add_interface_port read avm_read_address address Output 32
add_interface_port read avm_read_read read Output 1
add_interface_port read avm_read_readdata readdata Input 16
add_interface_port read avm_read_waitrequest waitrequest Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point write
# | 
add_interface write avalon start
set_interface_property write associatedClock clock_reset
set_interface_property write burstOnBurstBoundariesOnly false
set_interface_property write doStreamReads false
set_interface_property write doStreamWrites false
set_interface_property write linewrapBursts false

set_interface_property write ASSOCIATED_CLOCK clock_reset
set_interface_property write ENABLED true

add_interface_port write avm_write_address address Output 32
add_interface_port write avm_write_write write Output 1
add_interface_port write avm_write_writedata writedata Output 16
add_interface_port write avm_write_waitrequest waitrequest Input 1
# | 
# +-----------------------------------
